name: pizza_delivery_api
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.1.0
  injectable: ^1.0.4
  get_it: ^4.0.4
  mysql1: ^0.17.1
  aqueduct: ^4.0.0-b1

dev_dependencies:
  json_serializable: ^3.5.0
  build_runner: ^1.10.1
  injectable_generator: ^1.0.4
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1

scripts:
  watch: pub run build_runner watch
